packages:
  - packages/*

ignoredBuiltDependencies: []

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - core-js
  - core-js-pure
  - cypress
  - es5-ext
  - esbuild
  - less
  - lmdb
  - msgpackr-extract
  - nx
  - sharp
  - unrs-resolver

strictDepBuilds: true
