import { ExperienceEntryLike } from '../../types/ExperienceEntry';
import { ExperienceMapper } from '../ExperienceMapper';
import { EXPERIENCES } from './ntExperiences';
import { ctfHero } from './ctfHero';

interface IHeroFields {
  headline: string;
}

interface IButtonFields {
  label: string;
}

describe('Contentful Experience Mapper', () => {
  describe('mapCustomExperience', () => {
    it('should map experiences with a custom mapping function', () => {
      const experienceConfig = EXPERIENCES.map((experience) => {
        return ExperienceMapper.mapCustomExperience(experience, (variant) => ({
          id: variant.sys.id,
          headline: variant.fields.entryTitle,
          x: variant.fields.desktopImage,
        }));
      });

      expect(experienceConfig).toMatchSnapshot();
    });

    it('should not return any undefined values', () => {
      const experienceConfig = EXPERIENCES.map((experience) => {
        return ExperienceMapper.mapCustomExperience(experience, (variant) => ({
          id: variant.sys.id,
          headline: variant.fields.entryTitle,
          x: variant.fields.desktopImage,
        }));
      });

      expect(experienceConfig[0].description).not.toBeUndefined();
      expect(experienceConfig[0].name).not.toBeUndefined();
      expect(experienceConfig[0].audience?.description).not.toBeUndefined();
      expect(experienceConfig[0].audience?.name).not.toBeUndefined();
    });
  });

  describe('mapCustomExperienceAsync', () => {
    it('should map experiences with custom mapping function for variants including an async step', async () => {
      const mapped = await Promise.all(
        EXPERIENCES.map((experience) =>
          ExperienceMapper.mapCustomExperienceAsync(
            experience,
            async (variant) => {
              await new Promise((resolve) => setTimeout(resolve, 1000));
              return {
                id: variant.sys.id,
                headline: variant.fields.entryTitle,
                image: variant.fields.desktopImage,
              };
            }
          )
        )
      );

      mapped.forEach((mappedExperience) => {
        expect(mappedExperience.description).not.toBeUndefined();
        expect(mappedExperience.name).not.toBeUndefined();
        expect(mappedExperience.audience?.description).not.toBeUndefined();
        expect(mappedExperience.audience?.name).not.toBeUndefined();
        mappedExperience.components.forEach((component) => {
          component.variants.forEach((variant) => {
            expect('id' in variant).toBe(true);

            if ('headline' in variant) {
              expect(variant.headline).not.toBeUndefined();
              expect(variant.image).not.toBeUndefined();
            }
          });
        });
      });
    });
  });

  describe('mapExperience', () => {
    it('should not return any undefined values', () => {
      const experienceConfig = EXPERIENCES.map((experience) => {
        return ExperienceMapper.mapExperience(experience);
      });

      expect(experienceConfig[0].description).not.toBeUndefined();
      expect(experienceConfig[0].name).not.toBeUndefined();
      expect(experienceConfig[0].audience?.description).not.toBeUndefined();
      expect(experienceConfig[0].audience?.name).not.toBeUndefined();
    });

    it('should work with autogenerated types from contentful', () => {
      // eslint-disable-next-line @typescript-eslint/no-unused-vars
      const mapped = (ctfHero.fields.nt_experiences || [])
        .filter((entry) => ExperienceMapper.isExperienceEntry(entry))
        .filter(ExperienceMapper.isExperiment)
        .map((experience) => ExperienceMapper.mapExperience(experience));
    });

    // FIXME: Nothing is being asserted in this case
    it('should map experiences with Variant Interfaces', () => {
      const ntExperiences: ExperienceEntryLike<IHeroFields | IButtonFields>[] =
        [];

      // eslint-disable-next-line @typescript-eslint/no-unused-vars
      const mapped = ntExperiences
        .filter(ExperienceMapper.isExperienceEntry)
        .map((experience) => ExperienceMapper.mapExperience(experience));
    });
  });

  describe('isExperiment', () => {
    // FIXME: Nothing is being asserted in this case
    it('should find experiments', () => {
      const ntExperiences: ExperienceEntryLike<IHeroFields | IButtonFields>[] =
        [];

      // eslint-disable-next-line @typescript-eslint/no-unused-vars
      const mapped = ntExperiences
        .filter(ExperienceMapper.isExperienceEntry)
        .filter(ExperienceMapper.isExperiment)
        .map((experience) => ExperienceMapper.mapExperience(experience));
    });
  });
});
