name: Publish packages
on:
  release:
    types: [published]

jobs:
  setup:
    name: pnpm install 🛠️
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: ${{ github.ref }}

      - name: Install pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9

      - name: Use Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

  build:
    name: Build 📦
    runs-on: ubuntu-latest
    needs: setup
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Install pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9

      - name: Use Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Doppler CLI
        uses: dopplerhq/cli-action@4819d808ab99e5cde19a0637a16536a4038fad73 # v4

      - name: Build 📦
        run: >
          doppler run --mount .env -- pnpm nx run-many --target=build
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}

  lint:
    name: Lint 🎨
    runs-on: ubuntu-latest
    needs: setup
    timeout-minutes: 15
    steps:
      - name: Checkout Repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Install pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9

      - name: Use Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@afb73a62d26e41464e9254689e1fd6122ee683c1 # v5.0.1

      - name: Check Format
        run: pnpm nx format:check --verbose

      - name: Lint 🎨
        run: pnpm nx run-many --target=lint

  tests:
    name: Tests 🧪
    runs-on: ubuntu-latest
    needs: setup
    timeout-minutes: 15
    steps:
      - name: Checkout Repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Install pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9

      - name: Use Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Doppler CLI
        uses: dopplerhq/cli-action@4819d808ab99e5cde19a0637a16536a4038fad73 # v4

      - name: Test 🧪
        run: >
          doppler run --mount .env -- pnpm nx run-many --target=test
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}

  license-check:
    name: License check 📄
    runs-on: ubuntu-latest
    needs: setup
    timeout-minutes: 15
    steps:
      - name: Checkout Repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4.0.1
        id: changes
        with:
          filters: |
            lock:
              - 'pnpm-lock.yaml'

      - name: Install pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9

      - name: Use Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        if: steps.changes.outputs.lock == 'true'
        run: pnpm install --frozen-lockfile

      - name: Run License Checker
        if: steps.changes.outputs.lock == 'true'
        run: |
          echo "In case of error, please check ./docs/Licenses.md"
          pnpm exec license-checker --summary --production --relativeLicensePath --onlyAllow 'MIT;Apache-2.0;ISC;BSD-3-Clause;BSD-2-Clause;MIT*;Apache 2.0;Unlicense;:CC0-1.0;CC-BY-4.0;WTFPL;0BSD;UNLICENSED;Python-2.0;MPL-2.0;CC-BY-3.0;CC0-1.0'

  publish:
    name: Publish to NPM 🚀
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      id-token: write # This is required for NPM trusted publishers & provenance generation (https://docs.npmjs.com/trusted-publishers)
      contents: read # To checkout the repo
      actions: read
    needs:
      - build
      - lint
      - tests
      - license-check
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Install pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9

      - name: Use Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Doppler CLI
        uses: dopplerhq/cli-action@4819d808ab99e5cde19a0637a16536a4038fad73 # v4

      - name: Echo github event release metadatas
        run: echo "$JOB_CONTEXT"
        env:
          JOB_CONTEXT: ${{ toJson(github.event.release) }}

      - run: doppler run --mount .env -- ./tools/bump_and_publish_sdks.sh
        env:
          GITHUB_TAG: ${{ github.event.release.tag_name }}
          # we run nx build in the script, so we might need some env vars
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
